version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: tp4-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - spring-net

volumes:
  pgdata:

networks:
  spring-net:
